### ISSUE TITLE
We need a better first-time user experience

### ISSUE THREAD

**Issue by mwilck** [timberland-sig/edk2#3]
The current user experience for setting up the NVMe-oF boot attempt is frustrating. We need to boot the EFI disk with `startup.nsh` at least once to set up the attempt. The FW defaults to boot from CD-ROM (if there is any) or PXE v4/v6, otherwise. The PXEv6 connection attempt in particular can't be easily interrupted. The time span to hit the ESC key is extremely short, the user needs to hit the ESC key like crazy in order to be able to interrupt the default boot. Repeated ESC key strokes are almost guaranteed to interrupt the EFI shell boot, too, leaving the user (possibly) helpless at an EFI  shell prompt. When the user succeeds to reset the system, she needs to hit ESC crazily again, and the issue repeats.

I have experimented with qemu options like `boot c,menu=on`, without success.

This is related to https://github.com/timberland-sig/edk2-private/issues/76, but it's more important because https://github.com/timberland-sig/edk2-private/issues/76 affects only configuration changes whereas this issue here affects every user, in particular new users who start playing with the Timberland code.

Ideas:

* add a few seconds wait time for the user to hit ESC before trying any boot option
* disable PXE in our build (no idea what side effects that may have)
* modify default boot order, put EFI shell above PXE

**Comment by Douglas-Farley** [comment]
> The current user experience for setting up the NVMe-oF boot attempt is frustrating. We need to boot the EFI disk with `startup.nsh` at least once to set up the attempt.

This will be solved once we have an Hii interface.

> I have experimented with qemu options like `boot c,menu=on`, without success.

This has been buggy in my use for years, so i'm not surprised.

**Comment by Douglas-Farley** [comment]
@mwilck - Did you try exactly `-boot menu=on` or `-boot menu=on,splash-time=N`?

**Comment by mwilck** [comment]
I haven't tried `splash-time`. Will do.

**Comment by mwilck** [comment]
`splash-time=2000` works quite well. Closing.
